<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Telegram.Bot" Version="16.0.2" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Assets\cards\Card1.png" />
      <Content Include="Assets\cards\Card1.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Assets\cards\Card2.png" />
      <Content Include="Assets\cards\Card2.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Assets\cards\Card3.png" />
      <Content Include="Assets\cards\Card3.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

</Project>
